feat: add semantic release workflow (#18)
* feat: semantic release

* rename ci in hope of that it reflects in github

* fix formatting

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -1,14 +1,10 @@
-# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
-
-name: Continuous Integration (CI)
+name: Continuous Integration
 
 on:
   push:
     branches: ["main", "develop"]
   pull_request:
     branches: ["main"]
-  workflow_dispatch:
 
 jobs:
   build:
@@ -23,7 +19,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v3
+        uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}
 
@@ -37,13 +33,14 @@ jobs:
       - name: Install dependencies
         run: poetry install --sync --no-interaction
 
-      - name: Lint with flake8
+      - name: Check PR title with Commitizen
+        if: github.event_name == 'pull_request'
         run: |
-          # stop the build if there are Python syntax errors or undefined names
-          poetry run flake8 refcheck tests --count --select=E9,F63,F7,F82 --show-source --statistics
-          # exit-zero treats all errors as warnings.
-          poetry run flake8 refcheck tests --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
+          poetry run cz check --message "${{ github.event.pull_request.title }}" || 
+          (echo "Invalid PR title! Use Conventional Commit format (e.g., 'feat: add X')" && exit 1)
+
+      - name: Lint with Ruff
+        run: poetry run ruff check
 
       - name: Test with pytest
-        run: |
-          pytest
+        run: pytest
