fix formatting

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -34,10 +34,10 @@ jobs:
         run: poetry install --sync --no-interaction
 
       - name: Check PR title with Commitizen
-              if: github.event_name == 'pull_request'
-              run: |
-                poetry run cz check --message "${{ github.event.pull_request.title }}" || 
-                (echo "Invalid PR title! Use Conventional Commit format (e.g., 'feat: add X')" && exit 1)
+        if: github.event_name == 'pull_request'
+        run: |
+          poetry run cz check --message "${{ github.event.pull_request.title }}" || 
+          (echo "Invalid PR title! Use Conventional Commit format (e.g., 'feat: add X')" && exit 1)
 
       - name: Lint with Ruff
         run: poetry run ruff check
